export type WorkoutSplitType = 'push_pull_legs' | 'upper_lower' | 'full_body' | 'custom';
export type ExperienceLevelType = 'beginner' | 'intermediate' | 'advanced';

export interface ExploreExerciseItem {
  id: string;
  name: string;
  movementPattern: 'squat' | 'hinge' | 'push' | 'pull' | 'lunge' | 'carry' | 'core' | 'mobility';
  muscleGroup: string;
  sets: number;
  reps: string;
  restSeconds: number;
  rpe?: number | undefined;
  notes?: string | undefined;
  masterExerciseId?: string | undefined;
}

export interface ExploreDayItem {
  dayNumber: number;
  name: string;
  focus: string;
  exercises: ExploreExerciseItem[];
}

export interface ExplorePlanAuthor {
  name: string;
  role: string;
  avatar?: string | undefined;
  verified: boolean;
}

export interface ExploreProgression {
  baselineIntensity: string;
  progressionRule: string;
  increasePercent: number;
  conditions: string[];
}

export interface ExplorePrimaryExercise {
  name: string;
  masterExerciseId?: string | undefined;
  movementPattern?: string | undefined;
  muscleGroup?: string | undefined;
  mediaUrl?: string | undefined;
}

export interface ExplorePlanForkInfo {
  planId: string;
  authorName: string;
  planTitle?: string | undefined;
}

export interface ExplorePlanDto {
  id: string;
  title: string;
  description: string;
  split: WorkoutSplitType;
  frequencyDays: number;
  experienceLevel: ExperienceLevelType;
  equipment: string[];
  jointTags: string[];
  targetPersonas: string[];
  totalWeeklySets: number;
  author: ExplorePlanAuthor;
  cloneCount: number;
  days: ExploreDayItem[];
  summary?: string | undefined;
  safetyNotes?: string[] | undefined;
  progression?: ExploreProgression | undefined;
  isVerified: boolean;
  rating: number;
  reviewsCount: number;
  createdAt: string;
  primaryExercise?: ExplorePrimaryExercise | undefined;
  forkedFrom?: ExplorePlanForkInfo | undefined;
}

export const VERIFIED_EXPLORE_TEMPLATES: ExplorePlanDto[] = [
  {
    id: 'template-ppl-knee-safe',
    title: 'PPL Knee-Safe (Patellar Unloaded)',
    description:
      'Clinical push-pull-legs hyper-specialized for athletes with patellar tendon irritation or anterior knee pain. Emphasizes vertical shin squats, deep hinge loading, and scapular stabilization without shear stress.',
    split: 'push_pull_legs',
    frequencyDays: 3,
    experienceLevel: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'bench', 'cable_machine'],
    jointTags: ['Knee-Friendly', 'Low Patellar Shear', 'Hip Hinge Focused'],
    targetPersonas: [
      'Athletes with Patellar Tendinopathy',
      'Knee-Friendly Hypertrophy',
      'Runners with Knee Overuse',
    ],
    totalWeeklySets: 48,
    author: {
      name: 'PhysioCoach AI',
      role: 'Official Clinical System',
      verified: true,
    },
    cloneCount: 0,
    rating: 5.0,
    reviewsCount: 0,
    createdAt: '2026-06-01T00:00:00.000Z',
    isVerified: true,
    summary:
      'Eliminates anterior tibial shear by replacing quad-dominant deep forward knee travel with vertical-shin box squats and glute-biased hinges.',
    safetyNotes: [
      'Maintain vertical shin angle during single-leg lunges to shift load away from the patellar tendon.',
      'Stop Romanian deadlifts immediately if hamstrings lose tension or lumbar rounds.',
      'Tuck elbows 45° during all horizontal and incline presses to preserve glenohumeral clearance.',
    ],
    progression: {
      baselineIntensity: 'low-moderate',
      progressionRule: 'Increase load or reps by +10% after 2 pain-free sessions.',
      increasePercent: 10,
      conditions: ['Two pain-free sessions', 'Zero anterior knee aching post-workout'],
    },
    days: [
      {
        dayNumber: 1,
        name: 'Day 1: Push A (Chest, Delts & Triceps)',
        focus: 'Upper Body Hypertrophy & Neutral Pressing',
        exercises: [
          {
            id: 'ppl-d1-ex1',
            name: 'Incline Dumbbell Bench Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: 'Tuck elbows to 45 degrees to protect anterior capsule and rotator cuff.',
          },
          {
            id: 'ppl-d1-ex2',
            name: 'Standing Cable Chest Flyes',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Squeeze pectorals at mid-line without allowing shoulders to roll forward.',
          },
          {
            id: 'ppl-d1-ex3',
            name: 'Dumbbell Lateral Raises (Scapular Plane)',
            movementPattern: 'push',
            muscleGroup: 'shoulders',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Raise arms in the scapular plane (30° forward) with slight forward torso lean.',
          },
          {
            id: 'ppl-d1-ex4',
            name: 'Overhead Cable Triceps Extension',
            movementPattern: 'push',
            muscleGroup: 'triceps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            notes: 'Maintain neutral cervical spine and keep ribs clamped down.',
          },
          {
            id: 'ppl-d1-ex5',
            name: 'Serratus Wall Slides with Foam Roller',
            movementPattern: 'mobility',
            muscleGroup: 'serratus',
            sets: 3,
            reps: '10',
            restSeconds: 45,
            notes: 'Active upward scapular rotation and protraction at the top range.',
          },
        ],
      },
      {
        dayNumber: 2,
        name: 'Day 2: Pull A (Back, Rear Delts & Biceps)',
        focus: 'Scapulothoracic Strength & Upper Back Density',
        exercises: [
          {
            id: 'ppl-d2-ex1',
            name: 'Chest-Supported T-Bar Row',
            movementPattern: 'pull',
            muscleGroup: 'back',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: 'Drive elbows down and back with zero spinal jerking or lumbar extension.',
          },
          {
            id: 'ppl-d2-ex2',
            name: 'Neutral-Grip Lat Pulldown',
            movementPattern: 'pull',
            muscleGroup: 'lats',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Keep chest lifted and pull towards collarbone with neutral wrist alignment.',
          },
          {
            id: 'ppl-d2-ex3',
            name: 'Face Pulls with External Rotation',
            movementPattern: 'pull',
            muscleGroup: 'rear_delts',
            sets: 4,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Thumbs pointing backward at eye level, focus on rotator cuff activation.',
          },
          {
            id: 'ppl-d2-ex4',
            name: 'Incline Dumbbell Biceps Curl',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
            rpe: 8,
            notes: 'Full stretch at bottom, strict curl without swinging torso.',
          },
          {
            id: 'ppl-d2-ex5',
            name: 'Dead Hang (Spinal Decompression)',
            movementPattern: 'mobility',
            muscleGroup: 'spine',
            sets: 3,
            reps: '45s hold',
            restSeconds: 60,
            notes: 'Full passive hang for glenohumeral joint distraction and disc decompression.',
          },
        ],
      },
      {
        dayNumber: 3,
        name: 'Day 3: Legs A (Knee-Safe Posterior Chain)',
        focus: 'Glute, Hamstring & Calves with Zero Anterior Knee Shear',
        exercises: [
          {
            id: 'ppl-d3-ex1',
            name: 'Romanian Deadlift with Dumbbells',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: 'Hinge hips backward, keep knees soft, dumbbells skimming shins.',
          },
          {
            id: 'ppl-d3-ex2',
            name: 'Barbell Hip Thrust with Pad',
            movementPattern: 'hinge',
            muscleGroup: 'glutes',
            sets: 4,
            reps: '10-12',
            restSeconds: 90,
            rpe: 8,
            notes: 'Full glute lockout at top with tucked chin and vertical shins at 90 degrees.',
          },
          {
            id: 'ppl-d3-ex3',
            name: 'Bulgarian Split Squat (Vertical Shin Biased)',
            movementPattern: 'lunge',
            muscleGroup: 'quads',
            sets: 3,
            reps: '10 / leg',
            restSeconds: 75,
            rpe: 8,
            notes: 'Keep front shin vertical to load hip extensors rather than the patellar tendon.',
          },
          {
            id: 'ppl-d3-ex4',
            name: 'Seated Calf Raise',
            movementPattern: 'squat',
            muscleGroup: 'calves',
            sets: 4,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
            notes: '3-second isometric pause at the bottom stretch position.',
          },
          {
            id: 'ppl-d3-ex5',
            name: 'Copenhagen Plank Hold',
            movementPattern: 'core',
            muscleGroup: 'adductors',
            sets: 3,
            reps: '25s / side',
            restSeconds: 60,
            notes: 'Adductor and pelvic stability to enhance frontal-plane knee tracking.',
          },
        ],
      },
    ],
  },
  {
    id: 'template-desk-worker-posture',
    title: 'Upper/Lower Desk-Worker Posture',
    description:
      'Targeted posture-corrective hypertrophy program designed for desk-bound professionals. Reverses forward head carriage, relieves thoracic stiffness, and activates dormant glutes.',
    split: 'upper_lower',
    frequencyDays: 4,
    experienceLevel: 'beginner',
    equipment: ['dumbbells', 'cable_machine', 'bench', 'resistance_bands'],
    jointTags: ['Low Spine Load', 'Posture Corrective', 'Thoracic Mobility'],
    targetPersonas: [
      'Desk Workers with Back Pain',
      'Sedentary Professionals',
      'Forward Head & Kyphosis Recovery',
    ],
    totalWeeklySets: 66,
    author: {
      name: 'PhysioCoach AI',
      role: 'Official Clinical System',
      verified: true,
    },
    cloneCount: 0,
    rating: 5.0,
    reviewsCount: 0,
    createdAt: '2026-06-02T00:00:00.000Z',
    isVerified: true,
    summary:
      'Counteracts 8+ hours of daily sitting by prioritizing thoracic extension, lower trap strengthening, and glute medius activation.',
    safetyNotes: [
      'Press lumbar firmly into the floor during deadbugs to prevent anterior pelvic tilt.',
      'Maintain upright spine on box squats; avoid rounding forward when sitting back.',
      'Focus on scapular retraction before bending elbows on all rowing movements.',
    ],
    progression: {
      baselineIntensity: 'low-moderate',
      progressionRule: 'Increase load or reps by +10% after 2 pain-free sessions.',
      increasePercent: 10,
      conditions: ['Two pain-free sessions', 'No neck or low back tightness'],
    },
    days: [
      {
        dayNumber: 1,
        name: 'Day 1: Upper A (Thoracic Mobility & Horizontal Pulling)',
        focus: 'Scapular Retraction & Anterior Shoulder Opening',
        exercises: [
          {
            id: 'posture-d1-ex1',
            name: 'Dumbbell Neutral Flat Bench Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '10',
            restSeconds: 75,
            rpe: 7,
            notes: 'Palms facing inward protects AC joint and subacromial space.',
          },
          {
            id: 'posture-d1-ex2',
            name: 'Chest-Supported Neutral Dumbbell Row',
            movementPattern: 'pull',
            muscleGroup: 'back',
            sets: 4,
            reps: '12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Retract scapulae firmly before initiating elbow pull.',
          },
          {
            id: 'posture-d1-ex3',
            name: 'Prone Y-T-W Raises on Incline Bench',
            movementPattern: 'pull',
            muscleGroup: 'traps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            notes: 'Strengthens lower and middle trapezius for thoracic posture.',
          },
          {
            id: 'posture-d1-ex4',
            name: 'Half-Kneeling Single-Arm Cable Overhead Press',
            movementPattern: 'push',
            muscleGroup: 'shoulders',
            sets: 3,
            reps: '10 / side',
            restSeconds: 60,
            rpe: 7,
            notes: 'Glute engaged on down-knee leg to prevent lumbar hyperextension.',
          },
          {
            id: 'posture-d1-ex5',
            name: 'Deadbug Core Stabilization',
            movementPattern: 'core',
            muscleGroup: 'abdominals',
            sets: 3,
            reps: '12 / side',
            restSeconds: 45,
            notes: 'Press lumbar spine flush against the floor throughout.',
          },
        ],
      },
      {
        dayNumber: 2,
        name: 'Day 2: Lower A (Glute Activation & Pelvic Alignment)',
        focus: 'Glute Medius & Hamstring Strength',
        exercises: [
          {
            id: 'posture-d2-ex1',
            name: 'Trap Bar Deadlift (High Handles)',
            movementPattern: 'hinge',
            muscleGroup: 'glutes',
            sets: 4,
            reps: '8',
            restSeconds: 90,
            rpe: 8,
            notes: 'High handles and upright torso angle minimize lumbar moment arm.',
          },
          {
            id: 'posture-d2-ex2',
            name: 'Goblet Box Squat',
            movementPattern: 'squat',
            muscleGroup: 'quads',
            sets: 3,
            reps: '10',
            restSeconds: 75,
            rpe: 7,
            notes: 'Sit back gently onto box to reinforce neutral spinal mechanics.',
          },
          {
            id: 'posture-d2-ex3',
            name: 'Side-Lying Clamshell with Mini-Band',
            movementPattern: 'mobility',
            muscleGroup: 'glutes',
            sets: 3,
            reps: '15 / side',
            restSeconds: 45,
            notes: 'Pelvis rolled slightly forward to isolate gluteus medius.',
          },
          {
            id: 'posture-d2-ex4',
            name: 'Standing Dumbbell Calf Raises',
            movementPattern: 'squat',
            muscleGroup: 'calves',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
          },
          {
            id: 'posture-d2-ex5',
            name: 'Pallof Press with Cable or Resistance Band',
            movementPattern: 'core',
            muscleGroup: 'obliques',
            sets: 3,
            reps: '12 / side',
            restSeconds: 45,
            notes: 'Anti-rotation core brace resisting lateral pull.',
          },
        ],
      },
      {
        dayNumber: 3,
        name: 'Day 3: Upper B (Posterior Delts & Lat Expansion)',
        focus: 'Thoracic Extension & Rotator Cuff Health',
        exercises: [
          {
            id: 'posture-d3-ex1',
            name: 'Lat Pulldown with Wide Neutral Grip',
            movementPattern: 'pull',
            muscleGroup: 'lats',
            sets: 4,
            reps: '10',
            restSeconds: 75,
            rpe: 8,
            notes: 'Focus on lat contraction, avoid excessive backward lean.',
          },
          {
            id: 'posture-d3-ex2',
            name: 'Incline Dumbbell Row',
            movementPattern: 'pull',
            muscleGroup: 'back',
            sets: 3,
            reps: '12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Scapular protraction at stretch, strong squeeze at top.',
          },
          {
            id: 'posture-d3-ex3',
            name: 'Cable External Rotations at 90 Degrees',
            movementPattern: 'mobility',
            muscleGroup: 'rotator_cuff',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            notes: 'Keep elbow level with shoulder with controlled light tension.',
          },
          {
            id: 'posture-d3-ex4',
            name: 'Dumbbell Hammer Curl',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
          },
          {
            id: 'posture-d3-ex5',
            name: 'Foam Roller Thoracic Extensions',
            movementPattern: 'mobility',
            muscleGroup: 'spine',
            sets: 3,
            reps: '10',
            restSeconds: 45,
            notes: 'Support cervical spine with both hands during extension.',
          },
        ],
      },
      {
        dayNumber: 4,
        name: 'Day 4: Lower B (Hip Hinge & Unilateral Balance)',
        focus: 'Single-Leg Stability & Posterior Chain',
        exercises: [
          {
            id: 'posture-d4-ex1',
            name: 'Romanian Deadlift with Dumbbells',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 4,
            reps: '10',
            restSeconds: 90,
            rpe: 8,
            notes: 'Hinge back with flat spine, feeling hamstrings load.',
          },
          {
            id: 'posture-d4-ex2',
            name: 'Step-Ups with Dumbbells (Low Box)',
            movementPattern: 'lunge',
            muscleGroup: 'glutes',
            sets: 3,
            reps: '10 / side',
            restSeconds: 60,
            rpe: 7,
            notes: 'Drive purely through front heel, zero toe-push from trailing leg.',
          },
          {
            id: 'posture-d4-ex3',
            name: 'Swiss Ball Hamstring Curls',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            notes: 'Keep hips elevated and level throughout the entire curl.',
          },
          {
            id: 'posture-d4-ex4',
            name: 'Bird-Dog Quadruped',
            movementPattern: 'core',
            muscleGroup: 'spine',
            sets: 3,
            reps: '10 / side',
            restSeconds: 45,
            notes: 'Extend opposite arm and leg without lumbar rotation.',
          },
          {
            id: 'posture-d4-ex5',
            name: 'RKC Plank (Max Tension)',
            movementPattern: 'core',
            muscleGroup: 'core',
            sets: 3,
            reps: '20s max tension',
            restSeconds: 45,
            notes: 'Engage abs, glutes, and lats with maximal isometric tension.',
          },
        ],
      },
    ],
  },
  {
    id: 'template-fullbody-minimalist',
    title: '3-Day Full Body Minimalist',
    description:
      'High-yield, time-efficient compound training protocol. Maximum muscle stimulus and metabolic conditioning in 45 minutes with low joint wear.',
    split: 'full_body',
    frequencyDays: 3,
    experienceLevel: 'beginner',
    equipment: ['dumbbells', 'barbell', 'bench'],
    jointTags: ['Time-Efficient', 'Joint-Preserving', 'Full Body Balance'],
    targetPersonas: [
      'Time-Crunched Strength',
      'Busy Executives',
      'Total Body Reconditioning',
    ],
    totalWeeklySets: 45,
    author: {
      name: 'PhysioCoach AI',
      role: 'Official Clinical System',
      verified: true,
    },
    cloneCount: 0,
    rating: 5.0,
    reviewsCount: 0,
    createdAt: '2026-06-03T00:00:00.000Z',
    isVerified: true,
    summary:
      'Combines high-leverage compound movements into 45-minute structured sessions to stimulate strength and posture without excess joint fatigue.',
    safetyNotes: [
      'Limit deadlift volume when fatigued; stop sets with 2 reps in reserve (RPE 8).',
      'Use floor press to protect shoulders from extreme extension at bottom range.',
      'Maintain braced core on all carries to protect lumbar spine.',
    ],
    progression: {
      baselineIntensity: 'low-moderate',
      progressionRule: 'Increase load or reps by +10% after 2 pain-free sessions.',
      increasePercent: 10,
      conditions: ['Two pain-free sessions', 'Solid form on all compound lifts'],
    },
    days: [
      {
        dayNumber: 1,
        name: 'Day 1: Full Body A (Strength & Posture Foundation)',
        focus: 'Major Multi-Joint Compounds',
        exercises: [
          {
            id: 'fb-d1-ex1',
            name: 'Hex Bar Deadlift',
            movementPattern: 'hinge',
            muscleGroup: 'glutes',
            sets: 3,
            reps: '6',
            restSeconds: 120,
            rpe: 8,
            notes: 'Neutral grip and centered load reduce lumbar moment arm.',
          },
          {
            id: 'fb-d1-ex2',
            name: 'Incline Dumbbell Bench Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: '45-degree angle protects anterior capsule.',
          },
          {
            id: 'fb-d1-ex3',
            name: 'Chest-Supported Neutral Dumbbell Row',
            movementPattern: 'pull',
            muscleGroup: 'back',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Scapular retraction without spinal twisting.',
          },
          {
            id: 'fb-d1-ex4',
            name: 'Standing Overhead Dumbbell Carry',
            movementPattern: 'carry',
            muscleGroup: 'core',
            sets: 3,
            reps: '40m walk',
            restSeconds: 60,
            notes: 'Core brace, active shoulder elevation.',
          },
          {
            id: 'fb-d1-ex5',
            name: 'Hanging Knee Raises',
            movementPattern: 'core',
            muscleGroup: 'abs',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            notes: 'Posterior pelvic tilt at peak contraction.',
          },
        ],
      },
      {
        dayNumber: 2,
        name: 'Day 2: Full Body B (Hypertrophy & Posterior Chain)',
        focus: 'Unilateral Balance & Upper Back Density',
        exercises: [
          {
            id: 'fb-d2-ex1',
            name: 'Dumbbell Bulgarian Split Squats',
            movementPattern: 'lunge',
            muscleGroup: 'quads',
            sets: 3,
            reps: '8-10 / leg',
            restSeconds: 90,
            rpe: 8,
            notes: 'Forward torso lean loads glutes and protects front knee.',
          },
          {
            id: 'fb-d2-ex2',
            name: 'Dumbbell Floor Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '10',
            restSeconds: 75,
            rpe: 8,
            notes: 'Floor stops hyperextension of shoulders at bottom.',
          },
          {
            id: 'fb-d2-ex3',
            name: 'Neutral-Grip Lat Pulldown or Chin-Up',
            movementPattern: 'pull',
            muscleGroup: 'lats',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Dual handle pull to chest level.',
          },
          {
            id: 'fb-d2-ex4',
            name: 'Barbell Romanian Deadlift',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 3,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: 'Controlled 3-second eccentric lower.',
          },
          {
            id: 'fb-d2-ex5',
            name: 'Side Plank with Leg Lift',
            movementPattern: 'core',
            muscleGroup: 'obliques',
            sets: 3,
            reps: '30s / side',
            restSeconds: 45,
            notes: 'Glute medius and quadratus lumborum endurance.',
          },
        ],
      },
      {
        dayNumber: 3,
        name: 'Day 3: Full Body C (Capacity & Dynamic Stability)',
        focus: 'Tempo & Functional Symmetry',
        exercises: [
          {
            id: 'fb-d3-ex1',
            name: 'Goblet Squat (Tempo 3-1-1)',
            movementPattern: 'squat',
            muscleGroup: 'quads',
            sets: 3,
            reps: '10',
            restSeconds: 90,
            rpe: 7,
            notes: '3s lowering, 1s pause, explode up.',
          },
          {
            id: 'fb-d3-ex2',
            name: 'Push-Ups on Handles or Dumbbells',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Neutral wrist alignment, solid core plank.',
          },
          {
            id: 'fb-d3-ex3',
            name: 'Single-Leg Romanian Deadlift with Dumbbell',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 3,
            reps: '10 / leg',
            restSeconds: 60,
            rpe: 7,
            notes: 'Balance and hip stability.',
          },
          {
            id: 'fb-d3-ex4',
            name: 'Face Pulls with Cable or Band',
            movementPattern: 'pull',
            muscleGroup: 'rear_delts',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Rotator cuff and upper back posture balance.',
          },
          {
            id: 'fb-d3-ex5',
            name: "Farmer's Walk with Heavy Dumbbells",
            movementPattern: 'carry',
            muscleGroup: 'grip',
            sets: 3,
            reps: '50m walk',
            restSeconds: 60,
            notes: 'Grip strength and spinal posture integrity.',
          },
        ],
      },
    ],
  },
  {
    id: 'template-shoulder-safe-hypertrophy',
    title: 'Shoulder-Safe Hypertrophy',
    description:
      'Advanced muscle building split strictly engineered around rotator cuff biomechanics. Zero subacromial impingement, neutral grip angles, and heavy horizontal pulling balance.',
    split: 'upper_lower',
    frequencyDays: 4,
    experienceLevel: 'advanced',
    equipment: ['dumbbells', 'cable_machine', 'barbell', 'bench'],
    jointTags: ['Shoulder-Safe', 'Subacromial Space Preserving', 'Rotator Cuff Protective'],
    targetPersonas: [
      'Shoulder Impingement Athletes',
      'Overhead Athletes',
      'Lifters with AC Joint Irritation',
    ],
    totalWeeklySets: 66,
    author: {
      name: 'PhysioCoach AI',
      role: 'Official Clinical System',
      verified: true,
    },
    cloneCount: 0,
    rating: 5.0,
    reviewsCount: 0,
    createdAt: '2026-06-04T00:00:00.000Z',
    isVerified: true,
    summary:
      'Eliminates provocative overhead flaring and impingement triggers while delivering high-volume hypertrophy for upper and lower musculature.',
    safetyNotes: [
      'Use 30-degree incline with semi-supinated grips on dumbbell presses to widen subacromial space.',
      'Perform landmine press instead of strict overhead barbell presses for natural scapulohumeral rhythm.',
      'Never skip face pulls or external rotations to counterbalance chest and lat volume.',
    ],
    progression: {
      baselineIntensity: 'low-moderate',
      progressionRule: 'Increase load or reps by +10% after 2 pain-free sessions.',
      increasePercent: 10,
      conditions: ['Two pain-free sessions', 'Zero anterior shoulder pinching'],
    },
    days: [
      {
        dayNumber: 1,
        name: 'Day 1: Upper Push (Subacromial Space Preserving)',
        focus: 'Chest, Anterior Delts & Triceps with Neutral Pressing',
        exercises: [
          {
            id: 'sh-d1-ex1',
            name: 'Low-Incline Dumbbell Neutral Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: '30-degree incline, palms semi-supinated to avoid impingement.',
          },
          {
            id: 'sh-d1-ex2',
            name: 'Cable Crossover (High to Low Angle)',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Declined angle takes stress off supraspinatus tendon.',
          },
          {
            id: 'sh-d1-ex3',
            name: 'Landmine Single-Arm Press',
            movementPattern: 'push',
            muscleGroup: 'shoulders',
            sets: 3,
            reps: '10 / side',
            restSeconds: 75,
            rpe: 8,
            notes: 'Natural arcing movement path preserves glenohumeral clearance.',
          },
          {
            id: 'sh-d1-ex4',
            name: 'Cable Rope Triceps Pressdown',
            movementPattern: 'push',
            muscleGroup: 'triceps',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Flare ropes apart at bottom.',
          },
          {
            id: 'sh-d1-ex5',
            name: 'Scapular Push-Ups',
            movementPattern: 'mobility',
            muscleGroup: 'serratus',
            sets: 3,
            reps: '15',
            restSeconds: 45,
            notes: 'Activate serratus anterior to maintain upward scapular rotation.',
          },
        ],
      },
      {
        dayNumber: 2,
        name: 'Day 2: Lower (Posterior Chain & Quad Capacity)',
        focus: 'Knee & Hip Hypertrophy',
        exercises: [
          {
            id: 'sh-d2-ex1',
            name: 'Safety Bar Squat or Goblet Squat',
            movementPattern: 'squat',
            muscleGroup: 'quads',
            sets: 4,
            reps: '8',
            restSeconds: 90,
            rpe: 8,
            notes: 'Keeps shoulders in neutral position without external shoulder rotation stress.',
          },
          {
            id: 'sh-d2-ex2',
            name: 'Romanian Deadlift with Dumbbells',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: 'Deep hamstring stretch with flat back.',
          },
          {
            id: 'sh-d2-ex3',
            name: 'Leg Press (Feet High & Wide)',
            movementPattern: 'squat',
            muscleGroup: 'glutes',
            sets: 3,
            reps: '12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Glute and adductor emphasis.',
          },
          {
            id: 'sh-d2-ex4',
            name: 'Seated Calf Raises',
            movementPattern: 'squat',
            muscleGroup: 'calves',
            sets: 4,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
          },
          {
            id: 'sh-d2-ex5',
            name: 'Deadbug with Stability Ball',
            movementPattern: 'core',
            muscleGroup: 'core',
            sets: 3,
            reps: '12 / side',
            restSeconds: 45,
            notes: 'Lumbar-pelvic control and anti-extension bracing.',
          },
        ],
      },
      {
        dayNumber: 3,
        name: 'Day 3: Upper Pull (Scapulothoracic & Rotator Cuff)',
        focus: 'Back Thickness, Rear Delts & Scapular Retraction',
        exercises: [
          {
            id: 'sh-d3-ex1',
            name: 'Chest-Supported Neutral Grip Row',
            movementPattern: 'pull',
            muscleGroup: 'back',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
            rpe: 8,
            notes: 'Eliminates lower back strain, strict scapular squeeze.',
          },
          {
            id: 'sh-d3-ex2',
            name: 'Wide-Grip Cable Lat Pulldown (Neutral Grips)',
            movementPattern: 'pull',
            muscleGroup: 'lats',
            sets: 4,
            reps: '10-12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Pull to collarbone, avoid rounding forward.',
          },
          {
            id: 'sh-d3-ex3',
            name: 'Face Pull with Rope (High Pulley)',
            movementPattern: 'pull',
            muscleGroup: 'rear_delts',
            sets: 4,
            reps: '15-20',
            restSeconds: 60,
            rpe: 8,
            notes: 'External rotation focus, thumbs pointing backward at finish.',
          },
          {
            id: 'sh-d3-ex4',
            name: 'Incline Dumbbell Rear Delt Flyes',
            movementPattern: 'pull',
            muscleGroup: 'rear_delts',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
            notes: 'Thumbs facing downward/neutral, elbows soft.',
          },
          {
            id: 'sh-d3-ex5',
            name: 'Incline Dumbbell Biceps Curls',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
          },
        ],
      },
      {
        dayNumber: 4,
        name: 'Day 4: Lower & Core (Unilateral Stability & Hamstrings)',
        focus: 'Balance, Calves & Trunk Integrity',
        exercises: [
          {
            id: 'sh-d4-ex1',
            name: 'Dumbbell Walking Lunges',
            movementPattern: 'lunge',
            muscleGroup: 'quads',
            sets: 3,
            reps: '10 steps / leg',
            restSeconds: 75,
            rpe: 8,
            notes: 'Controlled knee tracking over second toe.',
          },
          {
            id: 'sh-d4-ex2',
            name: 'Lying Leg Curl',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 4,
            reps: '10-12',
            restSeconds: 75,
            rpe: 8,
            notes: 'Point toes forward, 2-second eccentric lower.',
          },
          {
            id: 'sh-d4-ex3',
            name: 'Dumbbell Step-Ups onto 18-inch Box',
            movementPattern: 'lunge',
            muscleGroup: 'glutes',
            sets: 3,
            reps: '10 / side',
            restSeconds: 60,
            rpe: 7,
            notes: 'Drive through front foot, glute focus.',
          },
          {
            id: 'sh-d4-ex4',
            name: 'Standing Dumbbell Calf Raises',
            movementPattern: 'squat',
            muscleGroup: 'calves',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
            rpe: 8,
          },
          {
            id: 'sh-d4-ex5',
            name: 'Suitcase Carry with Dumbbell',
            movementPattern: 'carry',
            muscleGroup: 'core',
            sets: 3,
            reps: '40m / side',
            restSeconds: 60,
            notes: 'Resist lateral flexion, strict upright posture.',
          },
        ],
      },
    ],
  },
  {
    id: 'template-classic-4day-hypertrophy',
    title: 'Classic 4-Day Bodybuilding Split',
    description:
      'High-volume 4-day aesthetic bodybuilding split: Chest & Biceps, Back & Triceps, Leg Power & Adductors, and Shoulders, Traps & Core with integrated Zone 2 treadmill conditioning.',
    split: 'custom',
    frequencyDays: 4,
    experienceLevel: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'cable_machine', 'bench'],
    jointTags: ['Hypertrophy Focused', 'Isolation Volume', 'Cardio Conditioning'],
    targetPersonas: [
      'Bodybuilding Hypertrophy',
      'Aesthetic Physique',
      'Muscle Mass & Symmetry',
      'Intermediate Lifters',
    ],
    totalWeeklySets: 119,
    author: {
      name: 'PhysioCoach AI',
      role: 'Official Clinical System',
      verified: true,
    },
    cloneCount: 0,
    rating: 5.0,
    reviewsCount: 0,
    createdAt: '2026-06-01T00:00:00.000Z',
    isVerified: true,
    summary:
      'Classic agonist/antagonist isolation split focusing on pectoral thickness, bicep peak development, lat width, quad volume, shoulder 3D roundness, and dedicated aerobic health.',
    safetyNotes: [
      'Rotator Cuff Protocol: Complete 2 sets of cable external rotations and scapular retractions prior to heavy incline pressing.',
      'Knee Joint Protection: Maintain controlled 2 to 3-second eccentric tempo on leg extensions and hack squats; do not bounce out of the hole or hyperextend knees at lockout.',
      'Shoulder Impingement Prevention: Perform upright rows with a wide grip and stop below shoulder height in the scapular plane.',
      'Lumbar Disc Safeguard: Hinge strictly at hips during Roman chair back extensions; never hyperextend past neutral alignment.',
      'Core Rotation Safety: Execute seated torso rotations and side flexions with controlled tempo and locked pelvis to protect lumbar facet joints.',
    ],
    progression: {
      baselineIntensity: 'moderate-high',
      progressionRule: 'Increase load by 2.5-5kg when all target reps are achieved with 1-2 RIR in reserve.',
      increasePercent: 5,
      conditions: ['All sets completed within target rep range', 'Clean biomechanical execution without form breakdown'],
    },
    days: [
      {
        dayNumber: 1,
        name: 'Day 1: Chest & Biceps',
        focus: 'Pectoral Density, Sternal Fibers & Biceps Peak Hypertrophy',
        exercises: [
          {
            id: 'c4d-d1-ex1',
            name: 'Smith Machine Incline Bench Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 4,
            reps: '10',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0025',
            notes: 'Bench angled at 30 degrees. Lower bar with controlled 2-second eccentric tempo to upper chest; press smoothly without locking elbows.',
          },
          {
            id: 'c4d-d1-ex2',
            name: 'Incline Dumbbell Bench Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0025',
            notes: 'Superset part 1. Set bench to 30-degree incline; tuck elbows 45 degrees to avoid subacromial impingement; deep stretch at bottom.',
          },
          {
            id: 'c4d-d1-ex3',
            name: 'Pec Deck Machine Flye',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '12',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0025',
            notes: 'Superset part 2. Keep slight elbow bend; focus on horizontal adduction; squeeze chest for 1 second at peak contraction.',
          },
          {
            id: 'c4d-d1-ex4',
            name: 'Flat Dumbbell Bench Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 4,
            reps: '10',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0025',
            notes: 'Tuck elbows at 45 degrees to protect anterior shoulder capsule; press in an arch without banging dumbbells together.',
          },
          {
            id: 'c4d-d1-ex5',
            name: 'Decline Barbell Bench Press',
            movementPattern: 'push',
            muscleGroup: 'chest',
            sets: 3,
            reps: '12',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0025',
            notes: 'Overloads lower pectoral fibers; lower bar under control to lower sternum; keep wrists stacked directly over forearms.',
          },
          {
            id: 'c4d-d1-ex6',
            name: 'Standing Barbell Biceps Curl',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 4,
            reps: '10',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Pin elbows firmly to sides; strictly avoid lumbar swinging or backward torso lean; squeeze biceps at apex.',
          },
          {
            id: 'c4d-d1-ex7',
            name: 'Alternating Dumbbell Biceps Curl',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 4,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Begin with neutral grip, supinate wrist outward at top of the movement for maximal biceps brachii activation.',
          },
          {
            id: 'c4d-d1-ex8',
            name: 'Standing Cable Biceps Curl',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Maintains continuous tension throughout the entire range of motion; pause for 1 second at full flexion.',
          },
          {
            id: 'c4d-d1-ex9',
            name: 'EZ-Bar Preacher Curl',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 3,
            reps: '10',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Superset part 1. Upper arms flush against pad; curl smoothly; stop just short of full elbow lockout at bottom to protect distal biceps tendon.',
          },
          {
            id: 'c4d-d1-ex10',
            name: 'Dumbbell Hammer Curl',
            movementPattern: 'pull',
            muscleGroup: 'biceps',
            sets: 3,
            reps: '10',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Superset part 2. Neutral grip targeting the brachialis and brachioradialis for forearm and arm thickness.',
          },
          {
            id: 'c4d-d1-ex11',
            name: 'Machine Abdominal Crunch',
            movementPattern: 'core',
            muscleGroup: 'abs',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0001',
            notes: 'Curl ribcage toward pelvis using abdominal contraction; exhale on flexion; avoid pulling with neck or arms.',
          },
        ],
      },
      {
        dayNumber: 2,
        name: 'Day 2: Back & Triceps + Cardio',
        focus: 'Lat Width, Mid-Back Thickness, Triceps Lateral Head & Aerobic Base',
        exercises: [
          {
            id: 'c4d-d2-ex1',
            name: 'Dumbbell Pullover',
            movementPattern: 'pull',
            muscleGroup: 'lats',
            sets: 4,
            reps: '10',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0007',
            notes: 'Lie perpendicular across bench; maintain slight bend in elbows; stretch lats over head within comfortable shoulder ROM; drive through elbows.',
          },
          {
            id: 'c4d-d2-ex2',
            name: 'Wide-Grip Lat Pulldown',
            movementPattern: 'pull',
            muscleGroup: 'lats',
            sets: 3,
            reps: '12',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0007',
            notes: 'Grip 1.5x shoulder width; pull bar smoothly to clavicle/upper sternum; do NOT pull behind the neck.',
          },
          {
            id: 'c4d-d2-ex3',
            name: 'One-Arm Dumbbell Row (Saw Row)',
            movementPattern: 'pull',
            muscleGroup: 'back',
            sets: 3,
            reps: '12',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0007',
            notes: 'Support knee and hand on flat bench; keep spine neutral; row dumbbell towards hip crease without rotating thoracic spine.',
          },
          {
            id: 'c4d-d2-ex4',
            name: 'Seated Cable Row (Close-Grip V-Bar)',
            movementPattern: 'pull',
            muscleGroup: 'back',
            sets: 4,
            reps: '10',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0007',
            notes: 'Torso stationary at 90 degrees; pull V-bar to navel; retract scapulae and squeeze mid-back; do not round lumbar on return.',
          },
          {
            id: 'c4d-d2-ex5',
            name: 'Triceps Cable Pushdown (Straight Bar)',
            movementPattern: 'push',
            muscleGroup: 'triceps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Pin upper arms against torso; push down smoothly until elbows are fully extended; isolate triceps lateral head.',
          },
          {
            id: 'c4d-d2-ex6',
            name: 'Rope Cable Triceps Pushdown',
            movementPattern: 'push',
            muscleGroup: 'triceps',
            sets: 3,
            reps: '10',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Spread rope tips outward at bottom lockout for maximal triceps long and lateral head recruitment.',
          },
          {
            id: 'c4d-d2-ex7',
            name: 'Single-Arm Cable Triceps Kickback',
            movementPattern: 'push',
            muscleGroup: 'triceps',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0055',
            notes: 'Constant cable line of pull; keep upper arm fixed parallel to torso; extend elbow completely with zero shoulder momentum.',
          },
          {
            id: 'c4d-d2-ex8',
            name: 'Seated Controlled Core Rotation (Broomstick Twist)',
            movementPattern: 'core',
            muscleGroup: 'obliques',
            sets: 4,
            reps: '30',
            restSeconds: 45,
            rpe: 7,
            masterExerciseId: '0001',
            notes: 'Seated with light bar behind shoulders; lock pelvis and rotate smoothly through thoracic spine; avoid ballistic jerking to protect lumbar discs.',
          },
          {
            id: 'c4d-d2-ex9',
            name: 'Treadmill Incline Cardio Walk',
            movementPattern: 'mobility',
            muscleGroup: 'legs',
            sets: 1,
            reps: '25 min',
            restSeconds: 60,
            rpe: 6,
            masterExerciseId: '0043',
            notes: 'Steady-state Zone 2 aerobic recovery on 3-5% incline at 4.5-5.5 km/h for cardiovascular conditioning and low joint impact.',
          },
        ],
      },
      {
        dayNumber: 3,
        name: 'Day 3: Legs & Abs',
        focus: 'Quad Overload, Hamstring Hinge, Adductor Width & Core Bracing',
        exercises: [
          {
            id: 'c4d-d3-ex1',
            name: 'Seated Leg Extension Machine',
            movementPattern: 'squat',
            muscleGroup: 'quadriceps',
            sets: 3,
            reps: '15',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0043',
            notes: 'Align knee joint axis with machine pivot; controlled 2-3 second eccentric lowering; avoid violent knee locking to protect patellar tendon.',
          },
          {
            id: 'c4d-d3-ex2',
            name: '45-Degree Leg Press',
            movementPattern: 'squat',
            muscleGroup: 'quadriceps',
            sets: 3,
            reps: '12',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0043',
            notes: 'Shoulder-width foot stance on platform; lower weight until knees reach 90 degrees; ensure lower back and sacrum stay pinned to pad.',
          },
          {
            id: 'c4d-d3-ex3',
            name: 'Hack Squat Machine',
            movementPattern: 'squat',
            muscleGroup: 'quadriceps',
            sets: 3,
            reps: '10',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0043',
            notes: 'Back flat against backrest; drive through midfoot and heels; knees track directly over toes; avoid knee cave (valgus).',
          },
          {
            id: 'c4d-d3-ex4',
            name: 'Dumbbell Goblet Squat',
            movementPattern: 'squat',
            muscleGroup: 'quadriceps',
            sets: 4,
            reps: '10',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0043',
            notes: 'Hold dumbbell vertically against sternum; squat deep between hips while keeping torso upright and spine neutral.',
          },
          {
            id: 'c4d-d3-ex5',
            name: 'Lying Leg Curl Machine',
            movementPattern: 'hinge',
            muscleGroup: 'hamstrings',
            sets: 3,
            reps: '15',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0085',
            notes: 'Keep hips pressed firmly into pad; curl heels towards glutes; 2-second eccentric return to safely overload hamstring musculotendinous junction.',
          },
          {
            id: 'c4d-d3-ex6',
            name: 'Dumbbell Sumo Squat (Adductors Focus)',
            movementPattern: 'squat',
            muscleGroup: 'adductors',
            sets: 3,
            reps: '10',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0043',
            notes: 'Wide stance with toes angled 30-45 degrees; squat down loading inner thighs and adductors; keep chest tall.',
          },
          {
            id: 'c4d-d3-ex7',
            name: 'Standing Controlled Lateral Flexion (Broomstick Side Bends)',
            movementPattern: 'core',
            muscleGroup: 'obliques',
            sets: 4,
            reps: '30',
            restSeconds: 45,
            rpe: 7,
            masterExerciseId: '0001',
            notes: 'Controlled lateral flexion of the spine engaging internal and external obliques; keep hips stationary and avoid lumbar twisting.',
          },
          {
            id: 'c4d-d3-ex8',
            name: 'Weighted Flat Bench Crunch',
            movementPattern: 'core',
            muscleGroup: 'abs',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0001',
            notes: 'Hold light weight plate on upper chest; curl shoulders and upper torso off bench; keep lumbar spine supported.',
          },
        ],
      },
      {
        dayNumber: 4,
        name: 'Day 4: Shoulders, Traps, Lower Back & Cardio',
        focus: 'Deltoid 3D Roundness, Trapezius Hypertrophy, Lumbar Integrity & Conditioning',
        exercises: [
          {
            id: 'c4d-d4-ex1',
            name: 'Standing Overhead Barbell Press (OHP)',
            movementPattern: 'push',
            muscleGroup: 'shoulders',
            sets: 3,
            reps: '12',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0071',
            notes: 'Press bar overhead in scapular plane; squeeze glutes and brace core to eliminate lumbar hyperextension; finish with bar over midfoot.',
          },
          {
            id: 'c4d-d4-ex2',
            name: 'Wide-Grip Upright Row (Scapular High Pull)',
            movementPattern: 'pull',
            muscleGroup: 'traps',
            sets: 4,
            reps: '10',
            restSeconds: 75,
            rpe: 8,
            masterExerciseId: '0071',
            notes: 'Take a wide grip (1.5x shoulder width); pull bar to lower sternum only, keeping elbows below shoulder height to eliminate subacromial impingement.',
          },
          {
            id: 'c4d-d4-ex3',
            name: 'Seated Dumbbell Shoulder Press',
            movementPattern: 'push',
            muscleGroup: 'shoulders',
            sets: 3,
            reps: '12',
            restSeconds: 90,
            rpe: 8,
            masterExerciseId: '0071',
            notes: 'Bench at 75-80 degrees; hold dumbbells 15 degrees forward in the scapular plane; press smoothly without clashing at apex.',
          },
          {
            id: 'c4d-d4-ex4',
            name: 'Standing Dumbbell Lateral Raise',
            movementPattern: 'push',
            muscleGroup: 'shoulders',
            sets: 4,
            reps: '10',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0071',
            notes: 'Slight 10-degree forward torso lean; raise arms to parallel with thumbs slightly higher than pinkies (no internal rotation) to protect supraspinatus.',
          },
          {
            id: 'c4d-d4-ex5',
            name: 'Incline Bench Rear Delt Dumbbell Flye',
            movementPattern: 'pull',
            muscleGroup: 'rear_delts',
            sets: 3,
            reps: '12',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0071',
            notes: 'Chest supported on 30-45 degree incline bench; sweep dumbbells outward with soft elbows; isolates posterior deltoid while unloading spine.',
          },
          {
            id: 'c4d-d4-ex6',
            name: 'Standing Cable Front Raise',
            movementPattern: 'push',
            muscleGroup: 'shoulders',
            sets: 4,
            reps: '10',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0071',
            notes: 'Low cable pulley between legs; raise handle to eye level with controlled tempo; isolate anterior deltoid head.',
          },
          {
            id: 'c4d-d4-ex7',
            name: 'Barbell Shrug',
            movementPattern: 'pull',
            muscleGroup: 'traps',
            sets: 3,
            reps: '10',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0071',
            notes: 'Elevate shoulders straight up towards ears; pause 1.5 seconds at top; do NOT roll shoulders backward to prevent cervical strain.',
          },
          {
            id: 'c4d-d4-ex8',
            name: 'Hyperextension / Roman Chair Back Extension',
            movementPattern: 'hinge',
            muscleGroup: 'lower_back',
            sets: 3,
            reps: '15',
            restSeconds: 60,
            rpe: 8,
            masterExerciseId: '0085',
            notes: 'Hinge strictly at hips; raise torso until body forms straight line from heels to head; do NOT hyperextend spine backward.',
          },
          {
            id: 'c4d-d4-ex9',
            name: 'Treadmill Incline Cardio Walk',
            movementPattern: 'mobility',
            muscleGroup: 'legs',
            sets: 1,
            reps: '25 min',
            restSeconds: 60,
            rpe: 6,
            masterExerciseId: '0043',
            notes: 'Steady-state Zone 2 aerobic recovery on 3-5% incline at 4.5-5.5 km/h for heart health and active recovery.',
          },
        ],
      },
    ],
  },
];

export function getVerifiedExplorePlans(): ExplorePlanDto[] {
  return VERIFIED_EXPLORE_TEMPLATES.map((tpl) => {
    const firstEx = tpl.days[0]?.exercises[0];
    return {
      ...tpl,
      primaryExercise: firstEx
        ? {
            name: firstEx.name,
            masterExerciseId: firstEx.masterExerciseId || firstEx.id,
            movementPattern: firstEx.movementPattern,
            muscleGroup: firstEx.muscleGroup,
          }
        : undefined,
    };
  });
}

export function findExplorePlanById(id: string): ExplorePlanDto | undefined {
  const match = VERIFIED_EXPLORE_TEMPLATES.find((tpl) => tpl.id === id);
  if (!match) return undefined;
  const firstEx = match.days[0]?.exercises[0];
  return {
    ...match,
    primaryExercise: firstEx
      ? {
          name: firstEx.name,
          masterExerciseId: firstEx.masterExerciseId || firstEx.id,
          movementPattern: firstEx.movementPattern,
          muscleGroup: firstEx.muscleGroup,
        }
      : undefined,
  };
}
